db:
  username: ${username.value:postgres}
  password: pass
  driver: PostgresDriver
  url: postgres:5432
  hosts:
    - localhost
    - 127.0.0.1
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3
  properties:
    first: 123
    second: 345
    third.value: Third

logging:
  level:
    root: INFO
    org.springframework.jdbc.core: TRACE
#    com.iwor.spring.database.pool.ConnectionPool: INFO
#  file:
#    name: 'logs/all.log'

server.port: 8081

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  profiles.active:
    - web
    - prod
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
#    show-sql: true
    hibernate:
#      ddl-auto: validate
      naming.physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties.hibernate:
      batch_size: 3
      fetch_size: 2
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
  jdbc:
    template:
      fetch-size: 3