db:
  username: postgres
  password: pass
  driver: PostgresDriver
  url: postgres:5432
  hosts:
    - localhost
    - 127.0.0.1
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3
  properties:
    first: 123
    second: 345
    third.value: Third

spring.profiles.active:
  - web
  - prod

logging:
  level:
    root: INFO
#    com.iwor.spring.database.pool.ConnectionPool: INFO
#  file:
#    name: 'logs/all.log'